### ISSUE TITLE
Cannot use import statement outside a module

### ISSUE THREAD

**Issue by hemfreitas11** [MatteZ02/discord-interactions#18]
```
C:\bkstore-bot>node test

C:\bkstore-bot\node_modules\discord-slash-commands-client\src\index.js:1     
import InteractionsClient from "./core/InteractionsClient";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:1053:16)
    at Module._compile (internal/modules/cjs/loader.js:1101:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\bkstore-bot\test.js:2:22) <--
![asdpng](https://user-images.githubusercontent.com/67705052/117195153-531f9380-adbb-11eb-8fc2-45c33311e920.png)

    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
```

Code used:

```
const Discord = require('discord.js')
const interactions = require('discord-slash-commands-client')

// create a new client 
const client = new Discord.Client()
const token = 'token'

// attach the interaction client to discord.js client
client.interactions = new interactions.Client(token, 'You bots user id')

// attach and event listener for the ready event
client.on('ready', () => {
console.log('Client is ready!')

// Create a new command that we can test
client.interactions
	.createCommand({
	name: 'ping',
	description: 'ping pong',
	}, '839563429794545664')
	.then(console.log)
	.catch(console.error)
})

// attach and event listener for the interactionCreate event
client.on('interactionCreate', async (interaction) => {
if (interaction.name === 'ping') {
	// send an initial reply
	await interaction.reply('Pong')

	// send a followup
	messageId = await interaction.reply({
	content: 'Follow up message',
	embeds: [new MessageEmbed().setDescription('Follow up test')],
	})

	setTimeout(() => {
	// delete initial reply
	interaction.delete()

	// edit 1st followup
	interaction.edit('Edited follow up message', messageId)
	}, 5000)
}
})

// login
client.login(token)
```
The bot has the right permissions, so i don't know if i'm doing something wrong here

![test](https://imgur.com/o7E1zno.png)

**Comment by joelnedev** [comment]
add this to your package.json
```json
"type": "module"
```

**Comment by hemfreitas11** [comment]
Still getting the error, here's my package.json
```
{
  "type": "module",
  "requires": true,
  "lockfileVersion": 1,
  "dependencies": {
    "@discordjs/collection": {
      "version": "0.1.6",
      "resolved": "https://registry.npmjs.org/@discordjs/collection/-/collection-0.1.6.tgz",
      "integrity": "sha512-utRNxnd9kSS2qhyivo9lMlt5qgAUasH2gb7BEOn6p0efFh24gjGomHzWKMAPn2hEReOPQZCJaRKoURwRotKucQ=="
    },
    "@discordjs/form-data": {
      "version": "3.0.1",
      "resolved": "https://registry.npmjs.org/@discordjs/form-data/-/form-data-3.0.1.tgz",
      "integrity": "sha512-ZfFsbgEXW71Rw/6EtBdrP5VxBJy4dthyC0tpQKGKmYFImlmmrykO14Za+BiIVduwjte0jXEBlhSKf0MWbFp9Eg==",
      "requires": {
        "asynckit": "^0.4.0",
        "combined-stream": "^1.0.8",
        "mime-types": "^2.1.12"
      }
    },
....
```

**Comment by hemfreitas11** [comment]
My bad, i added it to package-lock.json not package.json. 
After i put it in the right file i got this error: ```ReferenceError: require is not defined
    at file:///C:/bkstore-bot/test.js:1:17``` 
I changed 
```
const Discord = require('discord.js')
const interactions = require('discord-slash-commands-client')
```
to 
```
import Discord from 'discord.js'
import interactions from 'discord-slash-commands-client'
``` 
but now i'm back to the "Cannot use import statement outside a module" error, even with "type": "module" in package.json

**Comment by hemfreitas11** [comment]
Little update on this, i added 
```
import { createRequire } from 'module';
const require = createRequire(import.meta.url);
```
to the beginning of the .js file and now i  can use "require()" with ```"type":"module"```, and the bot finally managed to start.
But when i tested the command nothing happened. It seems the interactionCreate event is not working as the bot can't even console.log the interaction

![ttt](https://imgur.com/zxKFCoU.png)

**Comment by joelnedev** [comment]
Use ESM instead of CJS. i.e turn `const namespace = require("module");` into `import * as namespace from "module";`
More info can be found with a quick Google search for "ES Modules".

**Comment by hemfreitas11** [comment]
I tried with
```
import * as Discord from 'discord.js'
import { default as interactions } from 'discord-slash-commands-client'
```
yet same result as the previous method i used. 
```import  * as interactions from 'discord-slash-commands-client'``` doesn't work, i get the error "interactions.Client is not a constructor"
I'm pretty lost here, shouldn't it work even with require since all the example codes on the readme use it?

**Comment by joelnedev** [comment]
> I'm pretty lost here, shouldn't it work even with require since all the example codes on the readme use it?

Well, in the new version Matte completely switched the library to ESM and evidently forgot to update the README.md. So unless he sets it up similarly to discord.js, he can only use the export keyword and users can only use the import keyword. Same for your project with `.mjs` files or `"type": "module"`, it'll throw an error saying that require is not defined.

I'll look into it and try to make a PR so the package is available to those using CJS or ESM.
